// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "98ef0f65-aa83-4b4b-a976-25e385bc4ebb";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onShowMessageChange();
void onGetPressureChange();
void onSetPointChange();
void onVibrationChange();

String showMessage;
float getPressure;
float setPoint;
bool vibration;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(showMessage, READWRITE, ON_CHANGE, onShowMessageChange);
  ArduinoCloud.addProperty(getPressure, READWRITE, ON_CHANGE, onGetPressureChange);
  ArduinoCloud.addProperty(setPoint, READWRITE, ON_CHANGE, onSetPointChange);
  ArduinoCloud.addProperty(vibration, READWRITE, ON_CHANGE, onVibrationChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
